# docker-compose.yml

version: '3'

services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins-data:
